prospector-dev/prospector

- prospector/config.py
- prospector/formatters/text.py
- prospector/run.py
This replaces #68. Instead of modifying `Prospector` to support multiple paths, I've modified `prospector.run.main` to create a new `Prospector` instance for each input path. 
Detailed changes:
* If more than one path is provided and one of the paths is a directory, raise a `ValueError`
* Explain multi-input directory restriction in `--help`
* Add `Path` to each summary
* Don't print `Messages` header if there are no messages
> Add support for multiple positional path arguments

- prospector/formatters/text.py
If the character is not specified, the character output by the (default) 'text' formatter should not default to '0' but instead represent that no character was specified.
> Correctly formatting character in 'text' outputter

- prospector/config/__init__.py
- prospector/profiles/profile.py
Previously doc-warnings and test-warnings and similar were inherited even if a user provided their own profile, meaning there were some aspects that could not be changed by the profile.
Note that a separate pull request will improve the ability to restore the default behaviour of no test warnings by default and so on.
> Prospector-provided profiles should only be loaded if a profile is not provided by the user

- prospector/tools/pep8/__init__.py
Somewhere along the way, pep8 stopped ignoring the codes I had disabled in my custom profile. This PR fixes that.
> PEP8 Ignoring Profile Disabled Codes

- .prospector.yml
- prospector/postfilter.py
- prospector/run.py
- prospector/suppression.py
- prospector/tools/pylint/collector.py
- setup.py
- tests/suppression/test_suppression.py
- tests/suppression/testdata/test_ignore_file/test.py
- tests/suppression/testdata/test_ignore_lines/test.py
This adds better understanding and handling of pep8/flake8 style #noqa comments, and better merging of pylint message suppression.
> Improved message suppression

- prospector/profiles/profiles/no_doc_warnings.yaml
- prospector/profiles/profiles/strictness_low.yaml
- prospector/profiles/profiles/strictness_medium.yaml
- prospector/tools/profile_validator/__init__.py
- prospector/tools/pyflakes/__init__.py
- setup.py
They should match those of flake8, because why not.
http://flake8.readthedocs.org/en/latest/warnings.html
The profile-validator will also produce a warning to indicate how to rename the codes.
> Rename pyflakes codes

- prospector/config/__init__.py
- prospector/config/configuration.py
- prospector/profiles/profile.py
- prospector/profiles/profiles/default.yaml
- prospector/profiles/profiles/member_warnings.yaml
- prospector/profiles/profiles/no_member_warnings.yaml
The sad fact is that pylint's member warnings are wrong more often than they are right. As Prospector's aim is to reduce noise and make it really easy to get useful results, it seems pragmatic to simply turn those warnings off.
It can be turned on again in profiles with the member-warnings setting or the --member-warnings command line flag, but the default will now not include those warnings.
> Disabling warnings about members not existing by default

- prospector/tools/pyflakes/__init__.py
Recent changes broke the ability to have pyflakes ignore codes via a profile. This small change fixes that.
> Fixed ignores in pyflakes.

- prospector/formatters/__init__.py
- prospector/formatters/xunit.py
Added xunit output formatter. Not sure I used the correct attributes for the elements but it was enough to make prospector work with shippable.
This will fix #32
> added xunit formater support

- CHANGELOG.md
- prospector/__pkginfo__.py
- prospector/formatters/__init__.py
- prospector/formatters/xunit.py
- prospector/profiles/__init__.py
- prospector/profiles/profiles/flake8.yaml
- setup.py
Fixes #112 
This makes prospector also search in a directory named `.prospector` (in addition to `prospector`) when searching for profiles. This is the previous documented behaviour.
> Load profiles from .prospector directory

- prospector/message.py
- tests/test_message.py
Check if the character value is None and if so substitute it
with -1 when performing comparisons.
Fixes #116
> Don't compare integers to None in Location.__lt__

- prospector/formatters/xunit.py
- prospector/formatters/yaml.py
- tests/test_formatter_types.py
Under both Python 2 and Python 3, the output stream (actually
always `sys.stdout` in practice) is opened in text mode, and so
responsibility for handling the encoding lies with `.write`.
The XUnit and YAML backends were previously explicitly forcing an
encoding, which under Python 3 would mean `bytes` objects were
generated. This makes `sys.stdout` remarkably unhappy.
Solved by just removing the explicit encodings. Test case included.
Footnote: first contribution! Hopefully this is up to snuff?
> Fix #118: Always return `str` objects from formatter.render

- docs/profiles.rst
The current code is reading from 'output-format', not 'output_format'.
> Fix misnamed output-format in docs.

- prospector/suppression.py
File "C:\python34\Lib\runpy.py", line 170, in _run_module_as_main
"__main__", mod_spec)
File "C:\python34\Lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:project\__data__\venv\Scripts\prospector.exe\__main__.py", line 9, in <module>
File "C:project\__data__\venv\lib\site-packages\prospector\run.py", line 143, in main
prospector.execute()
File "C:project\__data__\venv\lib\site-packages\prospector\run.py", line 76, in execute
messages = self.process_messages(found_files, messages)
File "C:project\__data__\venv\lib\site-packages\prospector\run.py", line 36, in process_messages
return postfilter.filter_messages(filepaths, self.config.workdir, messages)
File "C:project\__data__\venv\lib\site-packages\prospector\postfilter.py", line 23, in …
> fix(suppression.py): file encoding problem

- prospector/tools/profile_validator/__init__.py
The profile-validator tool reports that `member-warnings` is not a valid setting.
> Make member-warnings a valid setting

- README.md
Currently the readme does not have information on how to install the tool. This may be a bit confusing for people who are unfamiliar with the tool, as they would have to go into the documentation for the tool to find out how to install it.
I paraphrased some of the [installation section](https://prospector.readthedocs.org/en/master/#installation) of the tool's main page on ReadTheDocs.
> Adding information on installation to the readme

- prospector/tools/pylint/__init__.py
Currently, if there is a [MASTER] load-plugins statement in pylintrc, the plugins will not get loaded.
> Load plugins from pylintrc as well

- prospector/tools/pep257/__init__.py
Problem
-------
Since its first introduction in bee710744d878b94c06617c6749d68c1bcebd4f7, the exception
handler for pep257's AllError exception uses an invalid attribute access for ``message``::
message=exc.message,
This mistake was likely caused by duplication of the pattern that precedes it::
message=error.message.partition(':')[2].strip(),
Solution
--------
We may simply access this string as ``.args[0]`` for all situations.  Alternatively, str(exc) should
provide the same benefit.  AllError class initializer makes the assumption of the first argument
as a string to be concatenated with, so we continue such assumption.
Note AllError class is deceptively named -- it is used to indicate an exception occurred while parsing
``__all__``, it is not a general purpose exception. A comment has …
> bugfix exception handler for pep257's AllError

- docs/usage.rst
- prospector/formatters/__init__.py
- prospector/formatters/vscode.py
Added new vscode formater that will be used by prospector plugin in vscode python extension. 
Updated docs related to vscode and my old xunit formater
> Added vscode formater and updated docs.

- setup.py
Patch from Debian out of reproducible builds: the list comprehension for _OPTIONAL['with_everything'] iterates over the previous dict entries non-deterministically, and the resulting entry order differs if build on different archs. And setuptools not yet sorts for egg.info/requires.txt. If you would like to take that in, welcome.
> sort with_everything deps for _OPTIONAL

- CHANGELOG.md
- CONTRIBUTORS.md
- MANIFEST.in
- docs/usage.rst
- prospector/__pkginfo__.py
- prospector/encoding.py
- prospector/formatters/__init__.py
- prospector/formatters/html.py
- prospector/formatters/templates/formatter.html
- setup.py
- tests/test_formatter_types.py
This changes added a new formatter to prospector current set. This format is a basic html using bootstrap to create an acceptable output that shows summary, messages and profile. I decided to use Jinja2 as template engine to make a more flexible html.
There is a default template in prospector/formatters/templates/formatter.html but exists the possibility of use a custom template that should be named formatter.html and must be in the same directory that prospector is running.
You can see an example of html output:
[prospector_html.zip](https://github.com/landscapeio/prospector/files/445072/prospector_html.zip)
> Added html formatter

- MANIFEST.in
- prospector/encoding.py
Merge with `master` to get some fixes.
Also add the license to the `MANIFEST.in` to ensure it is included in packages like `sdist`s.
> Include the license file

- prospector/exceptions.py
- prospector/tools/pylint/__init__.py
- prospector/tools/pylint/collector.py
The recent 1.7 version of pylint moved the exceptions to a different
submodule and this ensures everything works as expected.
Since there's been no activity on #205, I took it upon myself to update it as suggested there.
I did end up moving the pylint exception to the `prospector.exceptions` submodule, as I found it odd to sprinkle a `try .. except` everywhere.
I did not update the `_INSTALL_REQUIRES` in `setup.py` to up the version of pylint to `pylint>=1.7` or so. I think it should probably be done too.
This should also resolve #206.
> Fix missing 'UnknownMessage' exception

- prospector/tools/pylint/collector.py
Since **pylint 1.6.0**, no messages are reporter via prospector. See for example #188 and #183.
It's because of this commit - https://github.com/PyCQA/pylint/commit/dc071966398d26159773ec627c954cf651d3036e - which removes `handle_message` body in `BaseReporter`.
This pull requests fixes the issue.
> bugfix: fix Pylint collector (broken since Pylint 1.6.0)

- prospector/tools/pep257/__init__.py
After recent release of `pydocstyle` package prospector fails at import `PEP257Checker`.
This PR corrects import path.
> Fix import to match pydocstyle v.1.1.0

- prospector/tools/vulture/__init__.py
Since **vulture 0.9**, it no longer has `.file` attribute neither for `Item`, nor for `Vulture` class itself. It has changed to `.filename`. This pull requests adds support for 0.9 and up (currently, 0.10).
> feature: add support for vulture 0.9 and up.

- prospector/tools/pep257/__init__.py
- setup.py
This was relatively trivial to support and allows us to use prospector concurrently with tools that require pydocstyle 2.0.0
> pep257: Support pydocstyle >= 2.0.0

- docs/supported_tools.rst
The goal of this PR is to update the `supported tools` documentation at:  https://prospector.landscape.io/en/master/supported_tools.html with current URLs and project names.
> Update old URLs and project references

- docs/usage.rst
It appears to have been removed in https://github.com/landscapeio/prospector/commit/ffcb30cdee18cd29e66d70b844457be985656889
> Remove documentation refering to html formatting

- .travis.yml
- docs/contrib.rst
- tox.ini
> Add Python 3.5/3.6 support

- prospector/tools/pylint/__init__.py
- prospector/tools/pylint/linter.py
It's the way it's done by pylint in its own runner to load the config.
This way, the plugins correctly have access to their options.
Fixes #232
> Load pylint plugins before pylint config

- docs/Makefile
- docs/contrib.rst
- docs/index.rst
- docs/profiles.rst
- docs/supported_tools.rst
- Fix reST typo in docs (Closes #235)
- Update URLs in docs
> Fix typo and update URLs in docs

- prospector/tools/pylint/__init__.py
Fixes #231 
As mentioned in the issue above, there's no way to set inside `prospector.yml` the path for pylintrc. Instead, users have to rely on either having the `pylintrc` (or similar) being inside the project folder or through the command line option `--pylint-config-file` which can be error prone.
With this change, users can set `config_file` inside pylint options on `prospector.yml`. it'll look like:
```yaml
pylint:
options:
config_file: /home/xpto/projects/pylintrc
disable:
- bad-builtin
- too-few-public-methods
- missing-docstring
- star-args
```
Also, if users set `--pylint-config-file`, it'll have priority over what was set inside `prospector.yml`.
> Add option to set pylintrc inside prospector.yml

- .gitignore
- prospector/config/__init__.py
- prospector/config/configuration.py
- prospector/config/datatype.py
- prospector/profiles/profile.py
- prospector/run.py
Resolves #246.
As of now, there's no way to way to redirect output to files. This implementation was inspired on how it was described on #246 and how `pytest-cov` redirects its output. It's also possible to set multiple outputs for the same export, so if one runs `prospector -o xunit:output_file.xml:/home/xpto/output_file.xml` it'll write to both relative `output_file.xml` and absolute `/home/xpto/output_file.xml`. Multiple reports are also supported, so `prospector -o xunit:output_file.xml -o grouped` will write XUnit format to output to relative `output_file.xml` and grouped format on console.
> Feature write to file

- .gitignore
- .prospector.yml
- .travis.yml
- docs/supported_tools.rst
- prospector/__pkginfo__.py
- prospector/config/__init__.py
- prospector/config/configuration.py
- prospector/config/datatype.py
- prospector/profiles/profile.py
- prospector/run.py
- prospector/tools/__init__.py
- prospector/tools/mypy/__init__.py
- prospector/tools/pylint/__init__.py
- prospector/tools/pylint/linter.py
- setup.py
@chocoelho want to check over this?
This would create an new release with
1) several PRs merged in (mostly yours!)
2) moving versioning to more simple 1.0 - original versioning was just to make sure people knew it was a beta/work in progress but that was 5 years ago...
3) various fixes with latest versions of pylint/astroid
4) drops support for python 3.3 (deprecated so might as well ignore it)
> New release - 1.0

- prospector/tools/pylint/linter.py
When the previous change was implemented to allow the `config_from_file`
method within the pylint tools to use the `quiet` keyword in older
versions of pylint, the `quiet` keyword was added to the if block when
the pylint version is 2.0 or greater instead of the else block for when
the pylint version is less than (older) than 2.0
> Fix read_config_file using quiet keyword with older pylint versions

- prospector/blender_combinations.yaml
- prospector/config/__init__.py
- prospector/finder.py
- prospector/postfilter.py
- prospector/tools/pep8/__init__.py
- tests/finder/test_file_finder.py
- tox.ini
Resolves #257.
@carlio this will really need your input on it. To summarize, that was a point where `prospector` would give different results, this should be fixed. Also, `pep8linter` was not using all found files depending on the path it was called.
> Bugfix report different behavior based on path

- .travis.yml
- CHANGELOG.md
- prospector/__pkginfo__.py
- prospector/config/configuration.py
- prospector/tools/pylint/__init__.py
- setup.py
pylint-common is an unecessary dependency and adds additional 'cogs' to keep up to date with. It only has one augmentation which if necessary could be moved into prospector directly,
> Removing pylint common

- prospector/tools/pyroma/__init__.py
As there have been some changes in the available checks in Pyroma
recently, make the initialization more robust and future-proof
dynamically creating the mapping of available checks and Prospector
codes, using PYRUNKNOWN for eventual new checks not yet mapped in
Prospector.
Closes #276
> Fix Pyroma >= 2.4 initialization

- CHANGELOG.md
- prospector/__pkginfo__.py
- setup.py
After flake8 3.6.0 was released, prospector's dependency tree broke - see #285 
The quick solution was to pin pep8-naming to an older version which did not end up including flake8 as a dependency which is where the conflicts came from.
At least for now this will get builds working again for people.
> Version 1.1.4  -  fixing dependency resolution

- prospector/tools/pylint/linter.py
This change fixes the error `TypeError read_config_file() got an unexpected keyword argument quiet`
PyLint version 2 introduced the verbose argument in `read_config_file`, which defaults to `None`. I believe there is no reason to perform any version check, unless the `verbose` argument has to be set to anything other than `None`
> Remove unexpected argument from read_config_file

- setup.py
- tests/tools/pep8/test_pep8_tool.py
- tests/tools/pep8/testpath/test_space_tab.py
- tox.ini
Resolves #289 
It add pycodestyle 2.4.0 as being compatible with latest prospector and add a base pep8 test case.
> Update pycodestyle support

- prospector/tools/mypy/__init__.py
I am not sure if you like it, though I really like using `--strict` when lint with mypy.
> [mypy] Add strict option and fixed emacs output format

- .gitignore
- .pre-commit-config.yaml
- prospector/finder.py
- tests/finder/test_file_finder.py
See: https://github.com/PyCQA/prospector/issues/257#issuecomment-409510013
@carlio how do you feel about it?
> Fix working dir detection

- prospector/config/__init__.py
- setup.py
>  Adding pylint plugins back to fix --uses and --autodetect

- prospector/config/configuration.py
- prospector/config/datatype.py
[fixes #296] Splitting output format from output file(s) using generic separator rather than OS specific path separator
Rather than us `os.pathsep`, just specify that the prospector always takes a colon (though `;` still works in case people have that build config still)
> More generic path separator for --output-format output files

- .env
- .gitignore
- setup.py
Fixes #303 
Pinning pylint version as current release/master is not compatible with pylint 2.2.0 yet. For a quick bugfix release (as this is breaking builds everywhere) this will do for now and a proper fix will go into release 1.1.7 .
> Pin pylint to 2.1.1

- CHANGELOG.md
- setup.py
[fixes #302] Pin astroid to 2.0.4 as some dependencies do not work with latest astroid release
Related to #303 and #304 as well.
> Pin astroid version

- .env
- CHANGELOG.md
- prospector/__pkginfo__.py
Pinning pylint/astroid versions as sub-dependencies and prospector are not compatibile with most recent releases of both.
> Release 1.1.6.2

- setup.py
astroid 2 doesn't seem to be compatible with pylint-flask. This is
documented at https://github.com/jschaf/pylint-flask/pull/9.
pylint-flask 0.6 fixes this. prospector currently pulls in astroid 2.0.4
and pylint-flask 0.5. This commit fixes it.
> bump pylint-flask 0.5->0.6

- docs/profiles.rst
- prospector/profiles/profile.py
- prospector/tools/pylint/__init__.py
- tests/profiles/profiles/pylint_load_plugins.yaml
- tests/profiles/test_profile.py
This PR relates to #315.
This is simple way to load one tool specific option (load-plugins in pylint) from profile and use it. Any thoughts on how to use specific options in profile? Because for now I haven't found anything better.
> Add support pylint --load-plugins option in profile

- .travis.yml
Python 3.4 is EOL  https://devguide.python.org/devcycle/#end-of-life-branches
> Travis CI: Drop EOLed Python 3.4 and add 3.7 and nightly

- setup.py
I think that pinning is not needed anymore because the issue related to this pin (https://github.com/PyCQA/prospector/issues/302) was already fixed here:
https://github.com/PyCQA/pylint-django/commit/bfc44be336524a3bc95f06c4693e2a189726043d
> Try unpinning astroid

- prospector/tools/pylint/collector.py
Fix to support latest pylint message definition implementation. They're now providing the result as a list, thus the implementation similar to how they're using it internally.
c/c @carlio
> Pylint fix for message definitions usage

- prospector/tools/pylint/collector.py
- setup.py
c/c @carlio
together with #336 it solves the reported latest pylint +pylint-django we've been facing. Tested with a running project that faced the issues reported in #335. I've created this branch from #336 so there are two commits from there in here temporarily.
> Bump pylint django

- .travis.yml
- prospector/tools/mypy/__init__.py
- tests/tools/mypy/test_mypy_tool.py
Extracts a `format_message` to help unit testing
fix https://github.com/PyCQA/prospector/issues/339
> Support more kinds of mypy messages

- setup.py
Change restricted version from 2.0.0 to 2.1.0 to fix #307
> Change restricted version of pyflakes

- .gitignore
- CONTRIBUTORS.md
- Dockerfile
- prospector/tools/mypy/__init__.py
- tests/tools/mypy/test_mypy_tool.py
Mypy now returns a summary as the last line of the output. This patch filters them out.
fix https://github.com/PyCQA/prospector/issues/345
> Compatibility with mypy 0.730

- .travis.yml
- CONTRIBUTING.rst
- docs/contrib.rst
- setup.py
- tox.ini
This should fix failures with `pyflakes` (#353) and `pylint` when running `prospector` with Python 3.8 and marks Python 3.8 as supported by `prospector`.
#353
Aside from running the included tests with Python 3.8 I ran `prospector` against a large proprietary project which had `pylint` and `pyflakes` failing previously when running with Python 3.8.
> Add support for Python 3.8

- prospector/tools/mypy/__init__.py
- tests/tools/mypy/test_mypy_tool.py
My previous patch does not work because of [this silly change](https://github.com/PyCQA/prospector/pull/349/files#diff-a8f66834285bb48ac2142c47470c885aR92) I did after testing…
Somehow, I missed the `--no-error-summary` flag the first time I read https://github.com/PyCQA/prospector/issues/345. Thanks @ziyadedher for finding this!
Therefore, this PR reverts my previous attempt and passes one more flag.
I've tested this on mypy 0.720: it correctly ignores this flag. And it works with 0.740.
> Mypy 730 compat

- prospector/tools/pylint/linter.py
Simple typo in prospector/tools/pylint/linter.py 
Should read suppress rather than supress.
Closes #360 
Resolves a typo
> Fix simple typo: supress -> suppress

- CONTRIBUTORS.md
- setup.py
Bump the supported pycodestyle version from (<=2.4.0 to <=2.5.0). This aids in supporting flake8 (and other tools) which requires pycodestyle version 2.5.0. 
Update setup.py requirements
Issue #358 
Without this change, it is not possible to install flake8 and prospector in the same environment without a dependency clash.
* Ran test set as well as poetry install using flake8 and prospector
> #358 pycodestyle version support

- prospector/profiles/profile.py
- prospector/tools/profile_validator/__init__.py
This PR fixes how the output-target field defined in the configuration is used by prospector . Without this, the field is overwritten during profile dictionary merge and never used even if specified by the user.
This is one of the steps to achieve resolution of #[377](https://github.com/PyCQA/prospector/issues/377)
Based on the [profile.py](https://github.com/PyCQA/prospector/blob/master/prospector/profiles/profile.py#L49), there is a profile item that people can use to output the prospector results into a target directory/file.
I've been doing this in a project at the company I work to have the prospector's results in a reports directory.
> Adding output-target field when merging profiles

- CONTRIBUTORS.md
- prospector/blender_combinations.yaml
- prospector/tools/pyflakes/__init__.py
Prospector's mapping between pyflakes library error classes and error codes seems to be out of date with current pyflakes error list. All errors that are not in the list (for example, F405) gets converted to F999 code which makes it impossible to ignore individual errors.
Synchronize the list with the current version used in flake8.
> Update pyflakes error code list to the recent version

- CONTRIBUTING.rst
- CONTRIBUTORS.rst
- docs/usage.rst
- prospector/__main__.py
Re-adds `__main__.py` to enable executing as a module.
This was added in 0.12.6, and removed in 1.7.3.
Closes #496 
With this, prospector paths don't need to be added. 
In my experience, it also make integration with CI easier.
> Re-add `__main__.py` to enable executing as a module

- docs/usage.rst
There is a small typo in docs/usage.rst.
Should read `compatible` rather than `compatile`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, compatile -> compatible

- prospector/tools/pylint/linter.py
- pyproject.toml
pylint 2.15.7 changes `PyLinter._expand_files` to return `dict[str, ModuleDescriptionDict]` instead of `list[ModuleDescriptionDict]`. This PR changes `ProspectorLinter._expand_files` accordingly.
Closes #529
Prospector currently cannot run pylint.
I've verified that prospector can run pylint with this change applied.
I've run `pytest`locally. All tests fail, but they do that in master, too.
> Update types in ProspectorLinter

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .pre-commit-config.yaml
- prospector/tools/pylint/linter.py
Add prettier in pre-commit configuration for markdown files and the pre-commit configuration itself. This will avoid conflicts when rebasing by standardizing the code. Not applied on yaml because there's a lot of change.
> Add prettier in pre-commit configuration for markdown files

- prospector/tools/pylint/collector.py
By not setting an explicit output for the collector, pylint defaults to stdout, which then fails to serialize by dill in a multi-process execution environment. This change sets an explicit instance of StringIO for the output stream.
Closes #513 
This is just a guess, but I'm not familiar enough with the full context of what the `out` attribute in a pylint reporter does, how it's used, and whether it matters that we just disregard its contents.
Tested by applying this change to the 1.7.7 release, and running with pylint 2.15.5, with `jobs: 0` enabled for the pylint tool in `.prospector.yml`.
> Use StringIO in the pylint collector instead of sys.stdout

- prospector/run.py
We were missing the message parameter when re-raising the exception
when a tool raises.
When a tool failed, we are failing to pass the `message` parameter when re-raising, and that causes a chained exception
to happen:
```
File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/lib/python3.10/site-packages/prospector/run.py", line 95, in execute
messages += tool.run(found_files)
File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/lib/python3.10/site-packages/prospector/tools/pylint/__init__.py", line 253, in run
self._linter.check(self._args)
File "/home/dcaro/Work/wikimedia/operations-cookbooks/.tox/py3-prospector/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 696, in check
ast_per_fileitem = …
```
> run: fix missing parameter to exception

- CHANGELOG.rst
- pyproject.toml
@carlio I think this is the last thing to do for 1.8.0 ? (Do you want me to do the release ? How do we create the changelog from this : 
```
** File discovery fixes **
Finding paths and files to check has been replaced with a new version using ``pathlib`` - this should not result in any changes,
except fixing an issue where ``pylint`` and ``pydocstyle`` were inspecting the same file or directory twice sometimes.
However it may cause slightly different orders or reduce these duplicate warnings.
The behaviour of prospector should be unchanged, apart from some bugfixes related to the old file discovery mechanism.
Related bugs and PRs:
* `#480 <https://github.com/PyCQA/prospector/issues/480>`_
* `#417 <https://github.com/PyCQA/prospector/issues/417>`_
* `#199 …
```
> Upgrade the version to 1.8.0

- .github/workflows/tests.yml
- CHANGELOG.rst
- prospector/config/__init__.py
- pyproject.toml
- tests/utils.py
@Pierre-Sassoulas @carlio 
Some magic was done for `pathlib` in Python 3.10 but it seems to no longer be needed in Python 3.11.
> Add support for Python 3.11

- prospector/tools/pylint/linter.py
d5f2650960a75dbffeca705d1a7fc881fcce8a60 changed the file finding mechanism, this got lost when develop was merged.
#547
Tested manually that the error no longer occurs, also ran pytest and pre-commit. pre-commit passes, one test fails (test_total_errors). The test fails on master, too.
> Fix merge issue with file finding (fix #547)

- poetry.lock
- pyproject.toml
`poetry update coveralls pytest pytest-benchmark pytest-cov tzlocal coverage pre-commit tox twine`
This fixes the `self.threading.currentThread()` --> `self.threading.current_thread()` pytest warning in #546
> pyproject.toml: Upgrade tool.poetry.dev-dependencies

- prospector/tools/pyroma/__init__.py
#562
```bash
pip install -e . # on prospector folder
prospector --output=pylint sphinx_prompt # on a project that use pyroma (witch failed before)
```
> Fix pyroma dependency loop

- pyproject.toml
Loosen dependency on packaging from 22.0 to <23.0
This change will allow prospector to be installed alongside other common tools (e.g. black) use packaging >22.0.
This change was tested by running the pre-commit hooks and CI workflow.
> allow packaging >=22.0,<23.0

- .github/workflows/tests.yml
- docs/profiles.rst
- prospector/config/__init__.py
- prospector/profiles/profile.py
- tests/profiles/profiles/inherittest-module-file.yaml
- tests/profiles/profiles/inherittest-module.yaml
- tests/profiles/test_profile.py
- tests/prospector-profile-test/prospector_profile_test/alternate.yaml
- tests/prospector-profile-test/prospector_profile_test/prospector.yaml
- tests/prospector-profile-test/pyproject.toml
Add the possibility to use a profile shared throw a Python package.
Fix #459.
Be able to share a profile between different projects.
- I create a package with a profile (https://github.com/sbrunner/prospector-profile-duplicated)
- I created a `.prospector.yaml`configuration file that uses this profile
- Verify that we have:
- The default configuration
- The profile configuration (new)
- The project configuration (from `.prospector.yaml` file)
> Be able to load a profile from an external package

- CONTRIBUTORS.rst
- docs/profiles.rst
- prospector/tools/mypy/__init__.py
Mypy provides an API to use their daemon to speed up type checking. With this change, the `use-dmypy` configuration can be used to toggle usage of that API by prospector.
Mypy tends to be very slow on large repositories, using Mypy daemon makes it much faster.
I've run `prospector --with-tool mypy -t mypy <file>` on a `<file>` in a large repository with and without `use-dmypy` option. The difference was `0.57s` vs `17.44s` in favor of using dmypy.
> Add use-dmypy option to MypyTool

- docs/pre-commit.rst
Doc fix to use `-` instead of `_` to install mypy/bandit with prospector in pre-commit.
See #633. From [this discussion](https://github.com/landscapeio/prospector/issues/624#issuecomment-1600867046) seems to be related to how poetry resolves optional dependencies
#633
Makes docs clearer.
Used this updated pre-commit config in my own project, which was previously experiencing dependency install issues.
> Doc fix: Use hyphen to install prospector with mypy and bandit in pre-commit

- .github/workflows/tests.yml
- CHANGELOG.rst
- tests/tools/pyroma/test_pyroma_tool.py
This PR provides a mechanical fix/workaround (*ie* not a fix at the root cause, please see below for reasoning) for the failed test
**Testing steps**
- tested locally (on my machine) following the test steps from the Github Action (GA) workflow: result: 100% pass rate
- tested on GA via my personal fork: I replicated the test failure one can see on the main `master`
Clues: the `files.files` are identical on both machines; the `messages` indeed differ by two elements:
- Files and messages on local machine:
```
[PosixPath('/home/valeriu/prospector-fork/tests/tools/pyroma/testdata/pkg1/__init__.py'), PosixPath('/home/valeriu/prospector-fork/tests/tools/pyroma/testdata/pkg1/this_one_is_fine/setup.py'), PosixPath('/home/valeriu/prospector-fork/tests/tools/pyroma/testdata/pkg1/this_one_is_fine/_ …
```
> Mechanical fix/workaround for `tests/tools/pyroma/test_pyroma_tool.py`

- CHANGELOG.rst
- poetry.lock
- pyproject.toml
That would need to be rebased so we can release 1.10.4 by tagging the middle commit.
Closes #641
> Limit pylint to <3 while waiting for a new release of ``requirements-detector``

- docs/profiles.rst
- prospector/tools/mypy/__init__.py
* Add the ability to specify `check-untyped-defs` in the options section for mypy.
Feature request: https://github.com/landscapeio/prospector/issues/628
It is not required, but helping with better code quality is excellent.
The protocol followed has been: 
- Create a file with a function without types
- Run the current prospector version. 
- Get the message `"By default, the bodies of untyped functions are not checked. Consider using --check-untyped-defs  [annotation-unchecked]"`
- Apply the changes from the PR. 
- Add the option `check-untyped-defs` in the `prospector.yaml` such as:
```
mypy:
run: true
options:
ignore-missing-imports: true
check-untyped-defs: true
```
- Install it locally with `python3 install -e .` 
- Rerun, the prospector. 
- Get correct type inferences and checks.
> MyPy: Add the `check-untyped-defs` option for mypy.

- docs/conf.py
- prospector/blender.py
- prospector/config/configuration.py
Fix https://github.com/landscapeio/prospector/issues/656 and https://github.com/landscapeio/prospector/issues/646
Support Python 3.12 fully and easily
> Replace pkg_resources from setuptools by Python standard lib

- CHANGELOG.rst
- poetry.lock
- prospector/profiles/profile.py
- prospector/tools/pylint/__init__.py
- prospector/tools/pylint/linter.py
- pyproject.toml
- tests/tools/pylint/test_pylint_tool.py
Based on #671, fix some errors
> Use PyLint 3.0+

- prospector/tools/pylint/linter.py
With the new version I get:
```
File "/usr/local/bin/prospector", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.10/dist-packages/prospector/run.py", line 198, in main
prospector.execute()
File "/usr/local/lib/python3.10/dist-packages/prospector/run.py", line 73, in execute
for tool in self.config.get_tools(found_files):
File "/usr/local/lib/python3.10/dist-packages/prospector/config/__init__.py", line 68, in get_tools
config_result = tool.configure(self, found_files)
File "/usr/local/lib/python3.10/dist-packages/prospector/tools/pylint/__init__.py", line 114, in configure
config_messages, configured_by = self._get_pylint_configuration(
File "/usr/local/lib/python3.10/dist-packages/prospector/tools/pylint/__init__.py", line 200, in …
```
> Be able to see the Unrecognized options

- .github/workflows/release.yml
- .github/workflows/tests.yml
- poetry.lock
- pyproject.toml
This should be the last blocker for python 3.12 / pylint 3.0 support.
> [python 3.12 support] Drop python 3.8, upgrade pylint-django

- docs/profiles.rst
- prospector/tools/mypy/__init__.py
- tests/tools/mypy/test_profiles/mypy_bad_options.yaml
Just forward the options to mypy
fix #628
> Thread all the mypy options

- prospector/formatters/base_summary.py
- prospector/formatters/pylint.py
- prospector/formatters/text.py
- prospector/formatters/vscode.py
Add the summary of the standard output on the pylint and vscode output.
This summary provides useful information for all human friendly output.
> Have the summary also on pylint and vscode output 

- .pre-commit-config.yaml
Isort resolve some issues detected by flake8 => put is before
Prospector is slow => put it at last
By the way, what is the Prospector pre-commit for?, notes that:
- He always returns 0
- It's the master version who is running!
> Better pre-commit order

- .prospector.yml
- docs/profiles.rst
- prospector/config/__init__.py
- prospector/formatters/xunit.py
- prospector/tools/bandit/__init__.py
- prospector/tools/mccabe/__init__.py
- prospector/tools/mypy/__init__.py
- prospector/tools/pyright/__init__.py
Be able to pass options to Bandit without using a specific configuration filename
Profit on the profile's inheritance to be able to configure Bandit
On the Prospector code
> Be able to pass options to Bandit

- .prospector.yml
- docs/profiles.rst
- docs/supported_tools.rst
- poetry.lock
- prospector/config/__init__.py
- prospector/formatters/pylint.py
- prospector/profiles/profile.py
- prospector/tools/__init__.py
- prospector/tools/ruff/__init__.py
- pyproject.toml
- tests/tools/bandit/test_ruff_tool.py
Add Ruff as supported tool
I also modified the pylint output to:
- Avoid having a None in the message
- Add the character if available
- Be stronger
- Be more like the pylint output
And the profile merge to be able to better activate deactivate feature from inherited template, then I do a deep merge of the dictionaries that's in the option.
Fix #601
On prospector code
> Add Ruff as supported tool

- prospector/profiles/exceptions.py
- prospector/profiles/profile.py
`prospector --profile inexisting` war returning
```
Failed to run:
Could not find profile 111.
Search path: [:P:o:s:i:x:P:a:t:h:(:':/:h:o:m:e:/:s:b:r:u:n:n:e:r:/:w:o:r:k:s:p:a:c:e:/:p:r:o:s:p:e:c:t:o:r:':):,: :P:o:s:i:x:P:a:t:h:(:':/:h:o:m:e:/:s:b:r:u:n:n:e:r:/:w:o:r:k:s:p:a:c:e:/:p:r:o:s:p:e:c:t:o:r:/:p:r:o:s:p:e:c:t:o:r:/:p:r:o:f:i:l:e:s:/:p:r:o:f:i:l:e:s:':):], or in module 'prospector_profile_inexisting'
```
> Fix path list in error

- prospector/tools/ruff/__init__.py
- prospector/tools/utils.py
Currently, the option `--direct-tool-stdout` didn't work, this will make it work again,
> Fix --direct-tool-stdout

- prospector/blender.py
Currently, we can obtain this exceptions:
```
File "/home/runner/.cache/pre-commit/repocjulckrl/py_env-python3/bin/prospector", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/runner/.cache/pre-commit/repocjulckrl/py_env-python3/lib/python3.11/site-packages/prospector/run.py", line 200, in main
prospector.execute()
File "/home/runner/.cache/pre-commit/repocjulckrl/py_env-python3/lib/python3.11/site-packages/prospector/run.py", line 119, in execute
messages = self.process_messages(found_files, messages)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/.cache/pre-commit/repocjulckrl/py_env-python3/lib/python3.11/site-packages/prospector/run.py", line 30, in process_messages
messages = blender.blend(messages)
^^^^^^^^^^^^^^^^^^^^^^^ …
```
> Fix blender when line is None

- prospector/blender.py
- prospector/formatters/base.py
- prospector/formatters/grouped.py
- prospector/formatters/pylint.py
- prospector/message.py
- prospector/postfilter.py
- prospector/suppression.py
- prospector/tools/ruff/__init__.py
- tests/test_message.py
Currently, we get:
```
File "/home/runner/.cache/pre-commit/repoi1wsp71_/py_env-python3/lib/python3.13/site-packages/prospector/run.py", line 87, in execute
messages += tool.run(found_files)
~~~~~~~~^^^^^^^^^^^^^
File "/home/runner/.cache/pre-commit/repoi1wsp71_/py_env-python3/lib/python3.13/site-packages/prospector/tools/ruff/__init__.py", line 51, in run
for message in json.loads(completed_process.stdout):
~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
~~~~~~~~~~~~~~~~~~~~~~~^^^
File "/opt/hostedtoolcache/Python/3.13.0/x64/lib/python3.13/json/decoder.py", line 344, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end()) …
```
> Fix Ruff on error

- prospector/postfilter.py
- prospector/tools/pylint/collector.py
- pyproject.toml
- tests/utils.py
Add Ruff target Python version to make pyupgrad working
> Add Ruff target Python version, update code

- prospector/tools/utils.py
When using prospector (with pylint) on a Django project, Django runs into a problem testing whether the sysout/stderr is a TTY, but prospector wraps that in CaptureOutput. 
Please ignore that I can't spell "bugfix" in the branch name 🙄 
Fixes #703 
This PR implements that particular test for the case of prospector+Django
I had this problem on my own local project, and this code fixed it - it was a simple missing implementation on the wrapper class.
> Implement isatty() to make the CaptureOutput compatible with Django requirements 

- prospector/profiles/profiles/strictness_high.yaml
- prospector/profiles/profiles/strictness_medium.yaml
- prospector/profiles/profiles/strictness_veryhigh.yaml
I don't know how you manage the profiles, but those can be useful options for mypy,
what do you think?
> Add default options for mypy in the profiles

- prospector/finder.py
When we run, e.-g. `prospector test.py` currently the file test.py is filtered then the checks runs on all the files, it's relay not intuitive, and when we try to integrate it in another tool we get wrong results. 
With the change, a specified file can't be filtered.
> Don't filter manual selected file

- CONTRIBUTORS.rst
- docs/usage.rst
- prospector/formatters/__init__.py
- prospector/formatters/pylint_parseable.py
Added a new output format called `pylint-parseable` that follows this format: `{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}`.
Updated a comment in the existing pylint formatter to reflect the actual formatting generated by the formatter and updated the docs accordingly.
When trying to integrate prospector into a CI/CD tool I realized that the pylint output does not follow the same output format as when using `pylint --output-format=parseable` (see [Pylint 3.3.3 Documentation](https://pylint.readthedocs.io/en/stable/user_guide/usage/output.html) The existing format includes the character in the output which makes it difficult for it to be used as a drop-in-replacement. I added a new formatter that uses the format mentioned in the docs. I added a new formatter to avoid make a breaking …
> Added pylint-parseable formatter

- .pre-commit-config.yaml
- prospector/formatters/base.py
- prospector/formatters/pylint.py
- prospector/message.py
- prospector/tools/bandit/__init__.py
- prospector/tools/mypy/__init__.py
- prospector/tools/pylint/collector.py
- prospector/tools/ruff/__init__.py
Add more fields in the messages
#708
Have more information useful to implement a VS Code extension to display the error in the IDE.
> Add more fields in messages

- docs/profiles.rst
- docs/suppression.rst
- prospector/blender_combinations.yaml
- prospector/postfilter.py
- prospector/suppression.py
- prospector/tools/ruff/__init__.py
- tests/suppression/test_suppression.py
- tests/suppression/testdata/test_ignore_lines/test.py
- To completely ignore a line the `# noqa` should be alone
- To ignore a code we can use `# noqa: <code>` ad ruff do
- To ignore a code from a certain source use `# noqa: <source>.<code>`, this will also create an error if the ignored is not used.
Alternative of #714
- Be compatible with Ruff
- Have more control on message to be ignored
- Be notified on used ignore
Test added
> Better noqa interpretation

- prospector/blender_combinations.yaml
Add more blending correspondences
> More blending correspondances

- prospector/blender_combinations.yaml
The Ruff code F999 didn't exist, removing
See: https://docs.astral.sh/ruff/rules/
> Remove unexisting Ruff code

- tests/finder/testdata/venvs/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv/long_path_not_a_venv_long_path_not_a_v/README.txt
Cloning on Windows/using pre-commit hook results in an error for long filename (#744) in `tests/finder/testdata/venvs/long_path_not_a_venv/...`. Also tests failed for Windows.
Configuring git with `git config --system core.longpaths true` solves the problem for cloning, it will however not solve the usage as a pre-commit hook.
For testing pathutils the [current Test](https://github.com/prospector-dev/prospector/blob/master/tests/finder/test_pathutils.py#L30-L40) does not use the folder in testdata (also due to a typo in [L36](https://github.com/prospector-dev/prospector/blob/master/tests/finder/test_pathutils.py#L36) _"is_a_venv"_). The path is just passed to the _is_virtualenv_ method. Therefore i suggest to just delete the **long_path_not_a_venv** and its subfolders.
> Delete long_path_not_a_venv since not necessary

- poetry.lock
- pyproject.toml
In order to be able to track where the cryptography dependency is taken I need to be able to use tool I know better than poetry and so making the pyproject.toml more normalized is helpful. In order to do that I start by fixing the output of `poetry check`.
Before:
```
Warning: [tool.poetry.name] is deprecated. Use [project.name] instead.
Warning: [tool.poetry.version] is set but 'version' is not in [project.dynamic]. If it is static use [project.version]. If it is dynamic, add 'version' to [project.dynamic].
If you want to set the version dynamically via `poetry build --local-version` or you are using a plugin, which sets the version dynamically, you should define the version in [tool.poetry] and add 'version' to [project.dynamic].
Warning: [tool.poetry.description] is deprecated. Use …
```
> [poetry] Fix most deprecations without affecting the dependencies

- .github/workflows/pre-commit.yaml
- .pre-commit-config.yaml
- tests/config/test_config.py
- tests/config/test_datatype.py
- tests/execution/test_execution.py
- tests/finder/test_filefinder.py
- tests/finder/test_pathutils.py
- tests/formatters/test_formatter_types.py
- tests/is_python/test_is_python_module.py
- tests/profiles/test_profile.py
- tests/suppression/test_blender_suppression.py
- tests/suppression/test_suppression.py
- tests/test_blender.py
- tests/test_message.py
- tests/tools/bandit/test_bandit_tool.py
- tests/tools/mypy/test_mypy_tool.py
- tests/tools/pycodestyle/test_pycodestyle_tool.py
- tests/tools/pylint/parallel/one.py
- tests/tools/pylint/test_pylint_tool.py
- tests/tools/pyright/test_pyright_tool.py
- tests/tools/pyroma/test_pyroma_tool.py
- tests/tools/utils.py
- tests/tools/vulture/test_vulture_tool.py
- tests/utils.py
Remove the `--zero-exit` Prospector argument.
Complete the “exclude” to make the check pass.
> Remove Prospector --zero-exit argument

- docs/usage.rst
- prospector/formatters/__init__.py
- prospector/formatters/gitlab.py
Add GitLab formatter
https://github.com/prospector-dev/prospector/issues/765
When running prospector on GitLab CI/CD, it is not possible to use its report as is, because GitLab uses the "CodeClimate report format", which is not supported.
I tested these changes and got the expected result.
> Add GitLab formatter

- prospector/blender_combinations.yaml
Add blending about Use lazy % formatting in logging functions (PyLint) and 
Logging statement uses f-string (Ruff).
Better PyLint and Ruff integration
> Add blending for use lazy % formatting in logging functions
