prospector/autodetect.py
prospector/finder.py

len(libraries) < len(POSSIBLE_LIBRARIES) is most likely what was
intended. Fixes a TypeError.

Don't compare list() and int().

---

.prospector.yml
prospector/autodetect.py
prospector/blender_combinations.yaml
prospector/config/__init__.py
prospector/finder.py
prospector/formatters/pylint.py
prospector/tools/frosted/__init__.py
prospector/tools/pyflakes/__init__.py
prospector/tools/pylint/__init__.py

This PR contains various configuration changes, mild code changes and inline comments to disable warnings or otherwise fix code smells and errors found by running prospector on prospector.

Reduce warnings

---

CHANGELOG.md
docs/supported_tools.rst
prospector/config/__init__.py
prospector/finder.py
prospector/profiles/__init__.py
prospector/tools/__init__.py
prospector/tools/base.py
prospector/tools/profile_validator/__init__.py

This simple tool checks prospector profiles and warns about invalid or incorrect settings

Adding a "profile validator" tool

---

prospector/formatters/text.py
prospector/run.py

It should be up to the formatter to decide what to do when no messages were found

Allow rendering of empty messages if desired

---

docs/profiles.rst
docs/usage.rst

some corrections on the docs out of packaging this for Debian

corrected minor flaws and malformed table in docs

---

prospector/formatters/emacs.py

Allows compilation-mode regexes to correctly identify error locations.

Add character position to emacs formatter.

---

prospector/config/__init__.py

could be I am misunderstanding as I'm new to python, but this seems to fit what the usage says
Sorry to read about https://github.com/landscapeio/landscape-issues/issues/210
Hope you are recovering well. Best wishes.

fix apparent oversight with --max-line-length option

---

setup.py

lock pydocstyle requirement

---

CHANGELOG.md
prospector/__pkginfo__.py
prospector/exceptions.py
prospector/tools/pylint/__init__.py
prospector/tools/pylint/collector.py

I've updated the `CHANGELOG` file and bump the version in `prospector/__pkginfo__.py`.
I'm basing this branch from my PR #207. I always feel weird dictating a project's next version, which is why its a separate PR.
If you you'd prefer the changes in the #207, let me know and I'll adjust appropriately.

Update CHANGELOG and bump version

---

prospector/postfilter.py

Prepare relative paths

---

prospector/tools/pep8/__init__.py

pep8: do not exclude directories when they have a parent

---

prospector/tools/pylint/__init__.py
setup.py

This should fix the latest release with support for new Pylint version and Astroid releases.
Cherry picked from #309
Should resolve issue #331 
c/c @carlio

Hotfix for pylint module run

---

CHANGELOG.md
prospector/__pkginfo__.py

New version with changelog and bump in pkginfo file
c/c @carlio

Release 1.1.6.4

---

docs/profiles.rst
docs/supported_tools.rst
prospector/tools/__init__.py
prospector/tools/bandit/__init__.py
setup.py

Adds support for bandit as requested in #160 
1. In bandit/\_\_init\_\_.py I have raised errors. I'm not sure what the correct way to handle these issues are.
2. I've updated the documentation, with a very poor description of Bandit. And an updated count of tools.
3. I've not tested if `profile` and `config_file` options work. I have tested the other two options.

Add support for bandit.

---

README.rst
docs/index.rst
docs/supported_tools.rst

Improved the documentation to mention how to install on macos, or zsh

Zsh documentation update

---

pyproject.toml

Just fixed a wrong url in the pyproject.toml file ;D
Didn't raise an issue for this.
I've clicked the link on PyPI and it sent me to a user, so I decided to fix it ;D
I don't think it needs testing, let me know if it does.

Fixing wrong repository url in pyproject.toml

---

README.rst

Changes a markdown style link to RST in the README. I assume this was meant to be an RST link,  but if not feel free to close the PR. Also, I can change the branch to `develop` if desired.
I saw the link when perusing the code and thought I would offer a PR.

Convert markdown link to RST

---

docs/profiles.rst
prospector/tools/mypy/__init__.py

Added 'namespace-packages' flag in mypy config
Adding the --namespace-packages in the `mypy` api command

Added 'namespace-packages' flag in mypy config

---

docs/profiles.rst

Fixed link and table structure

---

prospector/tools/pylint/__init__.py
tests/tools/pylint/pylint_configs/pylintrc/.pylintrc
tests/tools/pylint/pylint_configs/pylintrc/testcode.py
tests/tools/pylint/pylint_configs/pylintrc2/pylintrc
tests/tools/pylint/pylint_configs/pylintrc2/testcode.py
tests/tools/pylint/pylint_configs/pyproject/pyproject.toml
tests/tools/pylint/pylint_configs/pyproject/testcode.py
tests/tools/pylint/pylint_configs/setup.cfg/setup.cfg
tests/tools/pylint/pylint_configs/setup.cfg/testcode.py
tests/tools/pylint/test_pylint_tool.py

Load pylint config from pyproject.toml / setup.cfg

---

prospector/profiles/profiles/no_pep8.yaml

Fix --no-code-style flag

---

CONTRIBUTING.rst

CONTRIBUTING.rst: nosetests --> pytest

---

.pre-commit-config.yaml

Use the real tag for prospector in pre-commit now that main is fixed

---

.pre-commit-config.yaml
prospector/autodetect.py
prospector/formatters/text.py
prospector/formatters/xunit.py
prospector/message.py
prospector/profiles/exceptions.py
prospector/profiles/profile.py
prospector/suppression.py
prospector/tools/bandit/__init__.py
tests/suppression/test_suppression.py
tests/test_blender.py
tests/tools/pylint/test_pylint_tool.py
tests/tools/pylint/testpath/absolute-import/pkg/file1.py

See https://github.com/PyCQA/prospector/pull/536#discussion_r1036402127

Add and apply pyupgrade 3.7 in pre-commit

---

prospector/config/__init__.py
prospector/tools/profile_validator/__init__.py

https://github.com/PyCQA/prospector/issues/546#issuecomment-1336709154
@gopackgo90 Your review, please.

Fix undefined name sre_constants in Python 3.11

---

.github/workflows/release.yml

Fix #545 see https://github.com/PyCQA/prospector/issues/545#issuecomment-1335058851

Downgrade poetry to permit extra option with underscores

---

prospector/config/__init__.py
prospector/tools/profile_validator/__init__.py

Fix discussed at https://github.com/PyCQA/prospector/pull/552#issuecomment-1337536709

Fix re._constants again

---

CONTRIBUTORS.rst
README.rst
docs/pre-commit.rst

Updated pre-commit documentation as per #566  
- Added some clarity on how to use `additional_dependencies` with pre-commit so people can C+P the example and have it work out of the box
- Also added example with configuration options of those `additional_dependencies` to facilitate the C+P nature of the examples
#566 
See details in #566
It's just documentation. If it rendered properly, it worked
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] All new and existing tests passed.

Added additional clarity on how to use additional_dependnecies w/ examples

---

docs/supported_tools.rst

mypy reached version 1.0.0 a while ago and is described as stable now rather than beta software by the authors: 
Mypy was experimental at the time these lines were written, but I wouldn't consider it experimental anymore, and I don't think the mypy authors do either, e.g. see https://github.com/python/mypy/pull/14251 .
#621
Readers of the docs unfamiliar with mypy may be dissuaded from using mypy due to it being described as 'experimental', which seems undesirable.
Just a removal of one word in the docs, so I haven't done testing. Please let me know if you think any is necessary.

Mypy is no longer experimental

---

.github/workflows/tests.yml
pyproject.toml

python 3.13 is out soon, let's see how it goes.

Add python 3.13 to the test matrice

---

.pre-commit-config.yaml
prospector/exceptions.py
prospector/formatters/pylint.py
prospector/formatters/vscode.py
prospector/formatters/xunit.py
prospector/suppression.py
prospector/tools/pylint/__init__.py
tests/execution/test_execution.py

Let pyupgrade upgrade the code for python 3.8.

Upgrade pre-commit hooks

---

pyproject.toml

Add Stéphane Brunner as a maintainer

---

poetry.lock
pyproject.toml

Remove no more needed types-setuptools

---

.github/workflows/tests.yml
.pre-commit-config.yaml
.prospector.yml
prospector/config/__init__.py
prospector/finder.py
prospector/formatters/base.py
prospector/message.py
prospector/profiles/profile.py
prospector/run.py
prospector/tools/profile_validator/__init__.py
prospector/tools/pyflakes/__init__.py
prospector/tools/pylint/__init__.py
prospector/tools/pylint/linter.py
prospector/tools/utils.py

Activate the prospector checks
Be more strict on the code to avoid regression

Prospector checks

---

prospector/formatters/base_summary.py
prospector/formatters/pylint.py
prospector/formatters/text.py
prospector/formatters/vscode.py

Be able to render profile on all textual output

---

prospector/formatters/base.py
prospector/formatters/emacs.py
prospector/formatters/grouped.py
prospector/formatters/pylint.py
prospector/formatters/text.py
prospector/formatters/vscode.py
prospector/formatters/xunit.py
prospector/message.py

Make path absolute to canonicalize them
Display the messages only when it's wanted
Currently, the pylint output sorts the messages to group them by filename, but it's not working because some files are absolute and some other relative.

Canonical path

---

prospector/tools/ruff/__init__.py

With Ruff we sometimes get messages from files that are ignored!
Be sure that the file isn't ignored
Tested on a project that impacted by the issue.

Fix error from ignored file with Ruff

---

prospector/blender_combinations.yaml

Update blending codes
Better Blending

Fix typo in Ruff code, add one more PyLint Ruff correspodance

---

README.rst

Updates documentation for pre-commit hooks.
Documentation is a bit outdated. See #746
Tested as pre-commit hook.

Update pre-commit hook in docs

---

.github/workflows/pre-commit.yaml
.github/workflows/tests.yml
.pre-commit-config.yaml
CHANGELOG.rst
prospector/config/configuration.py
prospector/profiles/profile.py
prospector/run.py
prospector/tools/mypy/__init__.py
prospector/tools/pyright/__init__.py
tests/tools/pylint/test_pylint_tool.py

Apparently the fail-fast option permitted for some error to go unfixed.

Remove the fail-fast option in pre-commit, fix existing issues

---

.pre-commit-config.yaml
.prospector.yml
prospector/profiles/profiles/strictness_veryhigh.yaml
tests/config/testdata/test_relative_ignores/profile_relative_ignores.yml
tests/execution/testdata/something/.prospector.yaml

prettier format jinja files pretty poorly, and djlint had some issue so I removed it.

[pre-commit] Add a hook for prettier 

---

.github/workflows/pre-commit.yaml
.prospector.yml
pyproject.toml
tests/config/test_datatype.py
tests/finder/test_filefinder.py
tests/finder/test_pathutils.py
tests/formatters/test_formatter_types.py
tests/is_python/test_is_python_module.py
tests/profiles/profiles/ignores.yaml
tests/profiles/test_profile.py
tests/suppression/test_suppression.py
tests/test_blender.py
tests/test_message.py
tests/tools/bandit/test_bandit_tool.py
tests/tools/mypy/test_mypy_tool.py
tests/tools/pycodestyle/test_pycodestyle_tool.py
tests/tools/pylint/test_pylint_tool.py
tests/tools/pyright/test_pyright_tool.py
tests/tools/vulture/test_vulture_tool.py
tests/utils.py

Check the tests files 
https://github.com/prospector-dev/prospector/pull/754#issuecomment-2796858891
Better coherence between the pre-commit and the Prospector command

Enable the warnings on the tests files

---

prospector/blender_combinations.yaml

Add some more Blending combinations
Better Blending

Add some Blending combinations
